### ISSUE TITLE
Как выбрать микросхемы РОМ

### ISSUE THREAD

**Issue by etomarat** [AlexZhAk/sr_cart#1]
Они же наверняка разные, по какому принципу искать и где? И если одна микруха это РОМ, то что вторая? Ты кажется в видео сказал что это РАМ, но на вид не похожа. 
Хотя бы маркировки скажи пожалуйста.

**Comment by AlexZhAk** [comment]
Так я же их даже назвал в сидео :)
ROM: https://www.promelec.ru/pdf/2383.pdf
RAM: http://pdf.dzsc.com/HY6/HY6264.pdf

**Comment by etomarat** [comment]
Спасибо! Видимо прослушал.
