### ISSUE TITLE
gerber

### ISSUE THREAD

**Issue by negativ72rus** [AlexZhAk/sr_cart#2]
Привет! Есть возможность выложить гербера для заказа плат?

**Comment by AlexZhAk** [comment]
> Привет! Есть возможность выложить гербера для заказа плат?

Он экспортируется из Sprint Layout.

**Comment by negativ72rus** [comment]
> > Привет! Есть возможность выложить гербера для заказа плат?
> 
> Он экспортируется из Sprint Layout.

Да, но нет Sprint Layout у меня. Иглом пользуюсь либо фьюжиком.
